import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import GlassCard from "@/components/glass/GlassCard";
import EmptyState from "@/components/glass/EmptyState";
import { ArrowLeft, FileText, Download, Search, Receipt, Shield, Bell, Loader2 } from "lucide-react";
import { useBank } from "@/store/bankStore";
import { generateMonthlyStatement, generate1099INT } from "@/lib/pdfDocuments";
import { ledgerProvider, friendlyProviderMessage, type ProviderStatement } from "@/lib/ledgerProvider";
import type { Transaction } from "@/types/transaction";

const categories = ["All", "Statements", "Tax Forms", "Notices", "Agreements"] as const;
type Category = (typeof categories)[number];

type DocRow = {
  id: string;
  name: string;
  category: Category;
  date: string;
  account: string;
  read: boolean;
  icon: typeof FileText;
  /** Shown under the row when the file is not an official bank document. */
  note?: string;
  download: () => void | Promise<void>;
};

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const parseTxDate = (raw: string): Date | null => {
  // Data uses formats like "Today, 3:12 PM", "Mar 12, 2026", "2026-03-12", etc.
  if (!raw) return null;
  if (/^today/i.test(raw)) return new Date();
  const d = new Date(raw);
  return isNaN(d.getTime()) ? null : d;
};

const periodLabel = (s: ProviderStatement) => {
  const d = s.periodEnd ? new Date(s.periodEnd) : s.periodStart ? new Date(s.periodStart) : null;
  if (!d || isNaN(d.getTime())) return "Statement";
  return `${MONTH_NAMES[d.getMonth()]} ${d.getFullYear()} Statement`;
};

const Documents = () => {
  const navigate = useNavigate();
  const { accounts, transactions } = useBank();
  const [activeCategory, setActiveCategory] = useState<Category>("All");
  const [searchQuery, setSearchQuery] = useState("");
  // Real statements produced by the banking partner. Until this resolves we do
  // not know whether official statements exist, so we don't fake any.
  const [statements, setStatements] = useState<ProviderStatement[] | null>(null);
  const [busyId, setBusyId] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    ledgerProvider
      .statements()
      .then((r) => { if (!cancelled) setStatements(r.statements ?? []); })
      .catch(() => { if (!cancelled) setStatements([]); });
    return () => { cancelled = true; };
  }, []);

  /** Opens the partner's own signed statement link (valid ~60 seconds). */
  const openStatement = async (s: ProviderStatement, format: "pdf" | "csv") => {
    setBusyId(`${s.id}-${format}`);
    try {
      const { url } = await ledgerProvider.statementUrl(s.id, format);
      window.open(url, "_blank", "noopener,noreferrer");
    } catch (e) {
      toast.error(friendlyProviderMessage(e));
    } finally {
      setBusyId(null);
    }
  };

  const rows = useMemo<DocRow[]>(() => {
    const list: DocRow[] = [];
    const today = new Date();
    const currentYear = today.getFullYear();

    // --- Official monthly statements from the bank -------------------------
    for (const s of statements ?? []) {
      const name = periodLabel(s);
      list.push({
        id: `bank-stmt-${s.id}`,
        name,
        category: "Statements",
        date: s.periodEnd ?? s.periodStart ?? "",
        account: s.accountName,
        read: true,
        icon: FileText,
        download: () => openStatement(s, s.hasPdf ? "pdf" : "csv"),
      });
    }

    // Months the bank has already issued an official statement for — never
    // duplicate those with a locally generated approximation.
    const officialMonths = new Set(
      (statements ?? [])
        .map((s) => (s.periodEnd ? new Date(s.periodEnd) : null))
        .filter((d): d is Date => !!d && !isNaN(d.getTime()))
        .map((d) => `${d.getFullYear()}-${d.getMonth()}`),
    );

    // --- Interim summaries for months the bank hasn't closed out yet -------
    // These are generated by Glass Bank from your activity, NOT by the bank,
    // and are labelled as such so nobody mistakes one for an official record.
    const acctList = [
      { key: "Checking", acc: accounts.checking },
      { key: "Savings", acc: accounts.savings },
    ].filter((a) => !!a.acc) as Array<{ key: string; acc: NonNullable<typeof accounts.checking> }>;

    for (const { key, acc } of acctList) {
      // Transactions carry the account's display name (e.g. "Everyday Checking").
      const mine = (transactions as Transaction[]).filter((t) => t.account === acc.name);
      const months = new Map<string, Date>();
      for (const t of mine) {
        const dt = parseTxDate(t.date);
        if (!dt) continue;
        months.set(`${dt.getFullYear()}-${dt.getMonth()}`, new Date(dt.getFullYear(), dt.getMonth(), 1));
      }
      const sorted = Array.from(months.values())
        .filter((d) => !officialMonths.has(`${d.getFullYear()}-${d.getMonth()}`))
        .sort((a, b) => +b - +a);

      sorted.forEach((d) => {
        const periodStart = new Date(d.getFullYear(), d.getMonth(), 1);
        const periodEnd = new Date(d.getFullYear(), d.getMonth() + 1, 0, 23, 59, 59);
        const label = `${MONTH_NAMES[d.getMonth()]} ${d.getFullYear()}`;
        const isCurrentMonth =
          d.getFullYear() === today.getFullYear() && d.getMonth() === today.getMonth();

        list.push({
          id: `stmt-${key}-${d.getFullYear()}-${d.getMonth()}`,
          name: `${label} activity summary`,
          category: "Statements",
          date: `${MONTH_NAMES[d.getMonth()].slice(0, 3)} 1, ${d.getFullYear()}`,
          account: key,
          read: true,
          icon: FileText,
          note: isCurrentMonth
            ? "Month in progress — your official statement is issued after month end"
            : "Generated by Glass Bank — not an official bank statement",
          download: () => {
            const txs = mine.filter((t) => {
              const dt = parseTxDate(t.date);
              return !!dt && dt >= periodStart && dt <= periodEnd;
            });
            generateMonthlyStatement({
              account: acc,
              transactions: txs,
              periodLabel: label,
              periodStart,
              periodEnd,
            });
            toast.success(`${label} summary downloaded`);
          },
        });
      });
    }

    // --- Year-end 1099-INT summaries --------------------------------------
    // Only for tax years the account was actually open in, and flagged as a
    // summary: the official form comes from the bank each January.
    const savings = accounts.savings;
    const openedYear = accounts.checking?.openedDate
      ? new Date(accounts.checking.openedDate).getFullYear()
      : currentYear;
    if (savings) {
      for (let taxYear = currentYear - 1; taxYear >= openedYear; taxYear--) {
        const interest = Number(
          (savings.interestEarned ?? Math.max(0, (savings.availableBalance * (savings.apy ?? 0)) / 100)).toFixed(2),
        );
        list.push({
          id: `1099int-savings-${taxYear}`,
          name: `1099-INT interest summary (${taxYear})`,
          category: "Tax Forms",
          date: `Jan 31, ${taxYear + 1}`,
          account: "Savings",
          read: true,
          icon: Receipt,
          note: "Summary for your records — the official 1099-INT is issued by the bank",
          download: () => {
            generate1099INT({
              account: savings,
              year: taxYear,
              interestEarned: interest,
              recipientName: savings.depositDetails?.holderName || "Account Holder",
            });
            toast.success(`1099-INT summary ${taxYear} downloaded`);
          },
        });
      }

    }


    const openedLabel = accounts.checking?.openedDate
      ? new Date(accounts.checking.openedDate).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })
      : "Jan 15, 2024";

    // --- Standing agreements & notices -----------------------------------
    const disclosures: Array<{ name: string; category: Category; date: string; body: string; icon: typeof FileText }> = [
      {
        name: "Account Opening Disclosure",
        category: "Agreements",
        date: openedLabel,
        body: "Terms, fee schedule, and account agreement disclosed at account opening.",
        icon: Shield,
      },
      {
        name: "E-Sign Consent",
        category: "Agreements",
        date: openedLabel,
        body: "Your consent to receive statements, notices, and agreements electronically.",
        icon: Shield,
      },
      {
        name: "Privacy Policy Update",
        category: "Notices",
        date: "Dec 15, 2025",
        body: "Updated privacy practices governing how Glass Bank collects and uses your information.",
        icon: Bell,
      },
    ];

    disclosures.forEach((d, idx) => {
      list.push({
        id: `disc-${idx}`,
        name: d.name,
        category: d.category,
        date: d.date,
        account: "All",
        read: true,
        icon: d.icon,
        download: () => {
          // Plain text, saved with a .txt extension: writing a text blob to a
          // .pdf produced a file no reader could open.
          const blob = new Blob(
            [`Glass Bank\n${d.name}\nIssued: ${d.date}\n\n${d.body}\n`],
            { type: "text/plain" }
          );
          const url = URL.createObjectURL(blob);
          const a = document.createElement("a");
          a.href = url;
          a.download = `${d.name.replace(/[^\w]+/g, "_")}.txt`;
          document.body.appendChild(a);
          a.click();
          a.remove();
          URL.revokeObjectURL(url);
          toast.success(`Downloaded ${d.name}`);
        },
      });
    });

    return list;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accounts, transactions, statements]);


  const filtered = rows.filter((d) => {
    const matchCat = activeCategory === "All" || d.category === activeCategory;
    const matchSearch = !searchQuery || d.name.toLowerCase().includes(searchQuery.toLowerCase());
    return matchCat && matchSearch;
  });

  return (
    <div className="min-h-dvh bg-background">
      <div className="px-5 sm:px-6 lg:px-0 pt-10 sm:pt-12 space-y-5 pb-10">
        <div className="flex items-center gap-3">
          <button onClick={() => navigate(-1)} className="h-11 w-11 rounded-full bg-secondary flex items-center justify-center">
            <ArrowLeft size={20} className="text-foreground" />
          </button>
          <h1 className="text-lg font-display font-bold text-foreground">Documents</h1>
        </div>

        <div className="relative">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
          <input value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="Search documents..." className="w-full pl-9 pr-4 py-2.5 rounded-xl bg-secondary text-foreground text-sm border-0 outline-none" />
        </div>

        <div className="flex gap-2 overflow-x-auto hide-scrollbar pb-1">
          {categories.map((cat) => (
            <button key={cat} onClick={() => setActiveCategory(cat)} className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap ${activeCategory === cat ? "bg-primary text-primary-foreground" : "bg-secondary text-muted-foreground"}`}>
              {cat}
            </button>
          ))}
        </div>

        {filtered.length === 0 ? (
          <EmptyState
            icon={FileText}
            title={rows.length === 0 ? "No documents yet" : "Nothing matches that search"}
            description={
              rows.length === 0
                ? "Monthly statements are generated automatically once your account has activity. Tax forms appear each January."
                : "Try another keyword, or switch back to the All category."
            }
            actions={
              rows.length === 0
                ? [{ label: "View activity", onClick: () => navigate("/activity") }]
                : [{ label: "Clear search", onClick: () => { setSearchQuery(""); setActiveCategory("All"); }, variant: "ghost" }]
            }
          />
        ) : (
        <GlassCard className="divide-y divide-border p-0 overflow-hidden">
          {filtered.map((doc) => {
            const Icon = doc.icon;
            const busy = busyId?.startsWith(doc.id.replace("bank-stmt-", ""));
            return (
              <button
                key={doc.id}
                onClick={() => void doc.download()}
                className="w-full flex items-center justify-between px-4 py-3.5 text-left hover:bg-secondary/40 transition-colors"
              >
                <div className="flex items-center gap-3 flex-1 min-w-0">
                  <Icon size={20} className="text-muted-foreground shrink-0" />
                  <div className="min-w-0">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-medium text-foreground truncate">{doc.name}</p>
                      {!doc.read && <div className="w-2 h-2 rounded-full bg-primary shrink-0" />}
                    </div>
                    <p className="text-xs text-muted-foreground">{doc.date} · {doc.account}</p>
                    {doc.note && <p className="text-[11px] text-muted-foreground/80 mt-0.5">{doc.note}</p>}
                  </div>
                </div>
                {busy
                  ? <Loader2 size={16} className="text-muted-foreground shrink-0 ml-2 animate-spin" />
                  : <Download size={16} className="text-muted-foreground shrink-0 ml-2" />}
              </button>
            );
          })}
        </GlassCard>

        )}
      </div>
    </div>
  );
};

export default Documents;
