// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabaseForUser.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.2";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauth() {
  return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
}

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my profile",
  description: "Fetch the signed-in user's banking profile (name, contact, address, account type).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/get-kyc-status.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_kyc_status_default = defineTool2({
  name: "get_kyc_status",
  title: "Get KYC status",
  description: "Return the signed-in user's identity-verification (KYC) status and submitted details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("kyc_profiles").select("id, legal_first_name, legal_last_name, country, city, employment_status, iberbanco_status_raw, created_at, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const status = data?.iberbanco_status_raw ?? (data ? "submitted" : "not_started");
    return {
      content: [{ type: "text", text: `KYC status: ${status}

${JSON.stringify(data ?? {}, null, 2)}` }],
      structuredContent: { status, profile: data }
    };
  }
});

// src/lib/mcp/tools/list-beneficiaries.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_beneficiaries_default = defineTool3({
  name: "list_beneficiaries",
  title: "List beneficiaries",
  description: "List the signed-in user's saved beneficiaries (people and accounts they send money to).",
  inputSchema: {
    favorites_only: z.boolean().optional().describe("Only return favorite beneficiaries."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ favorites_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    let q = sb.from("beneficiaries").select("*").eq("user_id", ctx.getUserId());
    if (favorites_only) q = q.eq("favorite", true);
    q = q.order("last_used_at", { ascending: false, nullsFirst: false }).limit(limit ?? 50);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { beneficiaries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-payment-requests.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_payment_requests_default = defineTool4({
  name: "list_payment_requests",
  title: "List payment requests",
  description: "List payment requests the signed-in user created, optionally filtered by status.",
  inputSchema: {
    status: z2.enum(["pending", "paid", "cancelled", "expired"]).optional(),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    let q = sb.from("payment_requests").select("id, amount_cents, currency, status, payer_email, payer_name, note, expires_at, created_at").eq("requester_id", ctx.getUserId());
    if (status) q = q.eq("status", status);
    q = q.order("created_at", { ascending: false }).limit(limit ?? 50);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { payment_requests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-payment-request.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var create_payment_request_default = defineTool5({
  name: "create_payment_request",
  title: "Create payment request",
  description: "Create a new payment request (invoice) from the signed-in user to a payer.",
  inputSchema: {
    amount_cents: z3.number().int().positive().describe("Amount in minor currency units (e.g. cents)."),
    currency: z3.string().length(3).optional().describe("ISO currency code, defaults to USD."),
    payer_email: z3.string().email().optional(),
    payer_name: z3.string().optional(),
    note: z3.string().max(500).optional(),
    expires_at: z3.string().datetime().optional().describe("ISO timestamp when the request expires.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("payment_requests").insert({
      requester_id: ctx.getUserId(),
      amount_cents: input.amount_cents,
      currency: (input.currency ?? "USD").toUpperCase(),
      payer_email: input.payer_email ?? null,
      payer_name: input.payer_name ?? null,
      note: input.note ?? null,
      expires_at: input.expires_at ?? null,
      status: "pending"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created payment request ${data.id} for ${(data.amount_cents / 100).toFixed(2)} ${data.currency}.` }],
      structuredContent: { payment_request: data }
    };
  }
});

// src/lib/mcp/tools/list-scheduled-transfers.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_scheduled_transfers_default = defineTool6({
  name: "list_scheduled_transfers",
  title: "List scheduled transfers",
  description: "List the signed-in user's upcoming and past scheduled transfers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("scheduled_transfers").select("id, kind, amount, currency, from_account, to_label, frequency, status, scheduled_for, next_run_at, last_run_at, memo").eq("user_id", ctx.getUserId()).order("next_run_at", { ascending: true, nullsFirst: false }).limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { scheduled_transfers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-support-tickets.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_support_tickets_default = defineTool7({
  name: "list_support_tickets",
  title: "List support tickets",
  description: "List the signed-in user's support tickets with status and priority.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("support_tickets").select("id, subject, category, priority, status, created_at, updated_at, last_agent_reply_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-support-ticket.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var create_support_ticket_default = defineTool8({
  name: "create_support_ticket",
  title: "Create support ticket",
  description: "Open a new support ticket on behalf of the signed-in user.",
  inputSchema: {
    subject: z4.string().min(3).max(200),
    body: z4.string().min(3).max(4e3),
    category: z4.enum(["account", "payments", "cards", "kyc", "security", "other"]).optional(),
    priority: z4.enum(["low", "normal", "high", "urgent"]).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauth();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("support_tickets").insert({
      user_id: ctx.getUserId(),
      subject: input.subject,
      body: input.body,
      category: input.category ?? "other",
      priority: input.priority ?? "normal",
      status: "open"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Opened support ticket ${data.id} \u2014 ${data.subject}` }],
      structuredContent: { ticket: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bbifvngdfeloitfubcnh";
var mcp_default = defineMcp({
  name: "glass-bank-mcp",
  title: "Glass Bank",
  version: "0.1.0",
  instructions: "Tools for the signed-in Glass Bank user: read profile and KYC status, list beneficiaries, list and create payment requests, list scheduled transfers, and manage support tickets. All actions run as the authenticated user with the same permissions as the app.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    get_kyc_status_default,
    list_beneficiaries_default,
    list_payment_requests_default,
    create_payment_request_default,
    list_scheduled_transfers_default,
    list_support_tickets_default,
    create_support_ticket_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
